version: '2.1'

orbs:
  slack: circleci/slack@4.4.2

references:
  only-release-branches: &only-dev-branches
    context:
      - slack_environment
    filters:
      branches:
        only: dev
  only-main-branch: &only-main-branch
    context:
      - slack_environment
    filters:
      branches:
        only: main
  only-staging-branches: &only-staging-branches
    context:
      - slack_environment
    filters:
      branches:
        only: staging

jobs:
     deployToDevFirebase:
          docker:
            - image: node:14
          steps:
            - checkout
            - run: echo "build steps"
            - run: npm install -g @angular/cli@latest firebase-tools
            - run: chmod +x sedconfig_uat.sh
            - run: ./sedconfig_uat.sh
            - run: npm install
            - run: npm run build
            - run: firebase projects:list --token "$FIREBASE_TOKEN"
            - run: firebase deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive
            # - run: cd functions && npm install
            # # - run: npm install
            # # - run: cd ..
            # - run: firebase deploy --only functions --token "$FIREBASE_TOKEN" --non-interactive
            # - slack/notify:
            #     event: fail
            #     mentions: '@sandeepyekkali'
            #     template: basic_fail_1
            # - slack/notify:
            #     event: pass
            #     template: success_tagged_deploy_1
     deployToProdFirebase:
          docker:
            - image: node:14
          steps:
            - checkout
            - run: echo "build steps"
            - run: npm install -g @angular/cli@latest firebase-tools
            - run: chmod +x sedconfig_prod.sh
            - run: ./sedconfig_prod.sh
            - run: npm install
            - run: npm run build
            - run: firebase projects:list --token "$FIREBASE_TOKEN"
            - run: firebase deploy --only hosting --token "$FIREBASE_TOKEN" --non-interactive
            # - run: cd functions && npm install
            # - run: firebase deploy --only functions --token "$FIREBASE_TOKEN"
            # - slack/notify:
            #     event: fail
            #     mentions: '@sandeepyekkali'
            #     template: basic_fail_1
            # - slack/notify:
            #     event: pass
            #     template: success_tagged_deploy_1
workflows:
  seller-portal-client-uat:
    jobs:
      - deployToDevFirebase: *only-dev-branches
  seller-portal-client-prod:
    jobs:
      - deployToProdFirebase: *only-main-branch
